### ISSUE TITLE
The name of new collection should be substring to avoid excessive length

### ISSUE THREAD

**Issue by bytimer** [TheZoc/EverythingDopusCLI#4]
When use some searching string like below (search video ext):
`ed.exe "D:\SOFT\\"  ext:3g2;3gp;3gp2;3gpp;amv;asf;avi;bdmv;bik;d2v;divx;drc;dsa;dsm;dss;dsv;dv;evo;f4v;flc;fli;flic;flv;hdmov;hlv;ifo;ivf;m1v;m2p;m2t;m2ts;m2v;m4b;m4p;m4v;mkv;mov;mp2v;mp4;mp4v;mpe;mpeg;mpg;mpls;mpv2;mpv4;mts;ogm;ogv;pss;pva;qt;ram;ratdvd;rm;rmm;rmvb;roq;rpm;smil;smk;swf;tp;tpr;ts;vob;vp6;webm;wm;wmp;wmv`

The name of new collection is toooo long so that it can not be created.
all files in search result will be added to the parent folder **EverythingDopus**

So the name should be substring or be Simplified.

**Comment by bytimer** [comment]
I found ：using everything 1.4 ， ed.exe cannot search macro ，for example: `ed zip:`   `ed audio:`
![image](https://github.com/TheZoc/EverythingDopus/assets/107342420/4166514b-b375-40ba-b6d0-8c32a3b0078c)

But using everything 1.5 , it work.
![image](https://github.com/TheZoc/EverythingDopus/assets/107342420/50d7eaa2-2252-486c-be9e-865b4c95fa4d)

**Comment by TheZoc** [comment]
Try this version please, it seems to work for me: https://github.com/TheZoc/EverythingDopus/releases/tag/v2.0-beta3

**Comment by TheZoc** [comment]
Oh wait, there are multiple issues in a single post again, I missed the top one.

Can you find what is the max length of the collection? If so I can enforce it when attempting to create a new collection

**Comment by bytimer** [comment]
the max length of the collection name may be 251.
for example:
`(2023-05-20 15-23-56) ext_3g2;3gp;3gp2;3gpp;amv;asf;avi;bdmv;bik;d2v;divx;drc;dsa;dsm;dss;dsv;dv;evo;f4v;flc;fli;flic;flv;hdmov;hlv;ifo;ivf;m1v;m2p;m2t;m2ts;m2v;m4b;m4p;m4v;mkv;mov;mp2v;mp4;mp4v;mpe;mpeg;mpg;mpls;mpv2;mpv4;mts;ogm;ogv;pss;pva;qt;ram;r`

the max length of whole path may be 274.
`coll://EverythingDopus/(2023-05-20 15-23-56) ext_3g2;3gp;3gp2;3gpp;amv;asf;avi;bdmv;bik;d2v;divx;drc;dsa;dsm;dss;dsv;dv;evo;f4v;flc;fli;flic;flv;hdmov;hlv;ifo;ivf;m1v;m2p;m2t;m2ts;m2v;m4b;m4p;m4v;mkv;mov;mp2v;mp4;mp4v;mpe;mpeg;mpg;mpls;mpv2;mpv4;mts;ogm;ogv;pss;pva;qt;ram;r`

**Comment by bytimer** [comment]
when I search dat in `C:\Program Files (x86)\Common Files\Adobe\Startup Scripts CC\Adobe Photoshop\photoshop_v2020`
the name is:
`(2023-05-23 08-09-32) _C__Program Files (x86)_Common Files_Adobe_Startup Scripts CC_Adobe Photoshop_photoshop_v2020_ dat`

If possible , I suggest you use only the final component of the path to generate the name.
for example, using `"photoshop_v2020" `as part of the name, not the whole path.

Although the max length is 251，I suggest you shorten it to 150.,if possible.

**Comment by bytimer** [comment]
I suggest :
"coll://EverythingDopus/(2023-05-26 12-27-54) "   ----length is 45 
 the final component of the path ，or the full path ---- make its length <=80
the search strings ----make its length <=100

so the length of the full name is <= 45+80+100=225

**Comment by TheZoc** [comment]
#3 Made this issue redundant
